services:
#    mongo_transaction.example:
#        class: MongoTransactionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  repository:
    class: Doctrine\ODM\MongoDB\DocumentManager


