<?php

namespace MongoTransactionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TransactionLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionLogsRepository extends DocumentRepository
{
}